### ISSUE TITLE
Directory Not Found Exception on case sensitive file systems

### ISSUE THREAD

**Issue by 45ninjas** [QuakeEye/Fluid-Sim#1]
DirectoryNotFoundException exception is thrown while reading shaders on a case sensitive file system/os.

`./shaders/Screen/screen.vert` does not exist. However `./shaders/screen/screen.vert` does.
```
Fluid-Sim
├── shaders
│   └── screen
│       ├── screen.frag
│       └── screen.vert
...
```

<details>
<summary>System.IO.DirectoryNotFoundException:</summary>

```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/tom/Documents
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Fluid_Sim.Window.LoadOpenGL(Surface screen) in /home/tom/Documents/Projects/git-repos/Fluid-Sim/Program.cs:line 100
   at Fluid_Sim.Window.OnLoad() in /home/tom/Documents/Projects/git-repos/Fluid-Sim/Program.cs:line 79
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Fluid_Sim.Program.Main(String[] args) in /home/tom/Documents/Projects/git-repos/Fluid-Sim/Program.cs:line 17
```

</details>

Running on Linux (Pop!_OS / Ubuntu / Debian).

Potential fixes:
- change ln 100 & 114 to reflect actual directory structure.
- rename `./shaders/screen` to `./shaders/Screen` to reflect what's written on ln 100 & 114 of Program.cs

**Comment by QuakeEye** [comment]
Thanks for this!

Fixed with #2
